### ISSUE TITLE
Main will recognise pygame as an import but debug wont.

### ISSUE THREAD

**Issue by Coding-64-Bit** [pythongame222/game#1]
![image](https://user-images.githubusercontent.com/117987625/203149673-879ff752-6749-49a5-abaa-f486c5b5c42f.png)
![image](https://user-images.githubusercontent.com/117987625/203149719-f195d1a0-c2fa-4a81-912b-4039c81766fb.png)

**Comment by githubfan** [comment]
Hm. Can't repeat this error on my system. Since the issue references pylint, just looks like a system error.

Two issues in the ss come from the display surface variable

![image](https://user-images.githubusercontent.com/47252616/203151031-6aa5eb38-2b8e-48f0-8751-0ebab6d7ea39.png)

**Comment by githubfan** [comment]
ignore this comment, just testing the webhook
